### ISSUE TITLE
Get-AWSCmdletName -AwsCliCommand is obsolete.

### ISSUE THREAD

**Issue by stknohg** [stknohg/aws-cli-eq-pwsh#2]
Since AWS Tools for PowerShell version 4, `Get-AWSCmdletName -AwsCliCommand` is obsolete.
There is no alternative way to get PowerShell Cmdlet from AWS CLI sub command name.

**Comment by bcdady** [comment]
Hi @stknohg - were you using this (presumably outside of what i can see in this repo) to maintain the collections within [02.ServiceMetadata.ps1](https://github.com/stknohg/aws-cli-eq-pwsh/blob/master/generator/02.ServiceMetadata.ps1)?

Per **AWS Tools for PowerShell User Guide** [Cmdlet Discovery and Aliases
](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-discovery-aliases.html) it appears that `Get-AWSCmdletName -ApiOperation` should be a viable alternative to the deprecated `-AwsCliCommand` parameter.

**Comment by stknohg** [comment]
@bcdady
Hi.

> were you using this (presumably outside of what i can see in this repo) to maintain the collections within 02.ServiceMetadata.ps1?

No. I use `Get-AWSCmdletName` only to get cmdlet name from AWS CLI command line. I maintain  02.ServiceMetadata.ps1 manualy.

> it appears that Get-AWSCmdletName -ApiOperation should be a viable alternative to the deprecated -AwsCliCommand parameter.

Thank you for your advice.
Now I trying to verify the code using `-Service` and `-ApiOperation` parameter.

```powershell
# example code

# current code (obsolete)
Get-AWSCmdletName -AwsCliCommand "aws ec2 describe-instances"

# is this equivalent above?
Get-AWSCmdletName -Service ec2 -ApiOperation describeinstances
```

**Comment by stknohg** [comment]
I verified to get same result using `-Service` and `-ApiOperation` paramteters.
